### ISSUE TITLE
Thank you tannn

### ISSUE THREAD

**Issue by danimesq** [Unisymbol/meta#1]
Hiii @tannn 👋

Were you searching for emojis like these: <img width="16px" src="https://raw.githubusercontent.com/googlefonts/noto-emoji/b2256e0f7dddfdff6e65f9c8b70f09934791e430/queue/emoji_bisexuality.svg"/> <img width="16px" src="https://raw.githubusercontent.com/googlefonts/noto-emoji/b2256e0f7dddfdff6e65f9c8b70f09934791e430/queue/emoji_uniaflag.svg"/> ?

- [repo](https://github.com/TheEmojiDAO/noto-emoji/tree/main/queue)

**Comment by tannn** [comment]
Hi @danimesq yes those look great!

Thanks for taking the initiative on this
